// Return the status of the API
GET http://localhost:3000/status HTTP/1.1

###

POST http://localhost:3000/v1/cards HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY29udGFjdEBleGFtcGxlLmNvbSIsInBob25lIjoiKzEtMjM0LTU2Ny04OTAiLCJyb2xlcyI6WyJjb21wYW55X2FkbWluIl0sImNvbXBhbnkiOjEsImlhdCI6MTcyOTg3NTg1MCwiZXhwIjoxNzMwMDQ4NjUwfQ.NhrX7vvSmJdd1dRkjIG7EL4nx6D4hFMbhIEX5-oXX5I

{
  "name": "John Doe",
  "email": "john.doe24@gmail.com",
  "phone": "1234567890"
}


###

POST http://localhost:3000/v1/companies HTTP/1.1
content-type: application/json

{
  "name": "Example Company",
  "description": "This is an example company.",
  "logo": "https://example.com/logo.png",
  "segment": "Technology",
  "website": "https://example.com",
  "cnpj": "12.346.678/0001-99",
  "email": "contact@example2.com",
  "password": "securepassword1232",
  "phone": "+1-234-567-890",
  "address": {
    "street": "123 Example St",
    "number": "456",
    "additional": "Suite 789",
    "neighborhood": "Example Neighborhood",
    "city": "Example City",
    "state": "EX",
    "zip": "12345-678",
    "country": "Example Country"
  },
  "lcard_rule": {
    "max_stamps": 10,
    "stamps_prize": "Free Coffee",
    "score_goal": 100,
    "score_goal_prize": "Discount Voucher",
    "score_booster": 1
  }
}

###

POST http://localhost:3000/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "contact@example.com",
  "password": "securepassword123"
}

###

GET http://localhost:3000/v1/auth/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY29udGFjdEBleGFtcGxlLmNvbSIsInBob25lIjoiKzEtMjM0LTU2Ny04OTAiLCJyb2xlcyI6WyJjb21wYW55X2FkbWluIl0sImNvbXBhbnkiOjEsImlhdCI6MTcyOTg3NTg1MCwiZXhwIjoxNzMwMDQ4NjUwfQ.NhrX7vvSmJdd1dRkjIG7EL4nx6D4hFMbhIEX5-oXX5I